version: "3.3"
services:
  c_db:
    container_name: c_db
    build:
      context: ./c_db
    ports:
      - 7144:3306
    volumes:
      - ./c_db/myqsl_deltron_data/:/var/lib/mysql
      - ./c_db/init:/docker-entrypoint-initdb.d/
  c_adminer:
    container_name: c_adminer
    image: adminer
    ports:
      - 8080:8080
